# Generated by Django 2.0.1 on 2018-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('XRP', 'XRP'), ('BTC', 'BTC'), ('LTC', 'LTC')], max_length=10)),
                ('bot', models.CharField(choices=[('BOT1', 'BOT1'), ('BOT2', 'BOT2'), ('BOT3', 'BOT3')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profit', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LastTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
