# Generated by Django 2.0 on 2018-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
