# Generated by Django 2.0.1 on 2018-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20180123_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttrade',
            name='bot',
            field=models.CharField(choices=[('BOT1', 'BOT1'), ('BOT2', 'BOT2'), ('BOT3', 'BOT3')], default='BOT1', max_length=10),
            preserve_default=False,
        ),
    ]
